// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbh5pGsuoQrlEbcETlQeVTD5HkE2ZE9wM',
    appId: '1:249808337572:web:4567d3029cd38464bc0431',
    messagingSenderId: '249808337572',
    projectId: 'flutterchatapp-698f1',
    authDomain: 'flutterchatapp-698f1.firebaseapp.com',
    storageBucket: 'flutterchatapp-698f1.appspot.com',
    measurementId: 'G-6W7C051TRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfHbyhLBLfAxT3XX4-Gt1zJHDVTtWO_rQ',
    appId: '1:249808337572:android:622716aa7d59dd8cbc0431',
    messagingSenderId: '249808337572',
    projectId: 'flutterchatapp-698f1',
    storageBucket: 'flutterchatapp-698f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuuipl6kxtIkNLu8IIBTW4prW0xq-QWTE',
    appId: '1:249808337572:ios:7df51f38be8b5f2bbc0431',
    messagingSenderId: '249808337572',
    projectId: 'flutterchatapp-698f1',
    storageBucket: 'flutterchatapp-698f1.appspot.com',
    iosBundleId: 'com.example.flutterChatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuuipl6kxtIkNLu8IIBTW4prW0xq-QWTE',
    appId: '1:249808337572:ios:3e562becbb5a158dbc0431',
    messagingSenderId: '249808337572',
    projectId: 'flutterchatapp-698f1',
    storageBucket: 'flutterchatapp-698f1.appspot.com',
    iosBundleId: 'com.example.flutterChatapp.RunnerTests',
  );
}
